### ISSUE TITLE
Problem when trying to bundle using gem from github

### ISSUE THREAD

**Issue by L4r1k** [umts/aggressive_inventory#2] opened 2016-07-15 13:03 UTC
![gemfile](https://cloud.githubusercontent.com/assets/19558495/16874939/650f8c08-4a6a-11e6-9a87-a83168ed35b0.png)
![error](https://cloud.githubusercontent.com/assets/19558495/16874942/69166f4c-4a6a-11e6-820d-ce43e5499adb.png)

**Comment by werebus** [comment] 2016-07-15 13:05
Sounds like "[TODO](https://github.com/umts/aggressive_inventory/blob/master/aggressive_inventory.gemspec#L12)" is not a description.

**Comment by L4r1k** [comment] 2016-07-15 13:09
Works when local aggressive_inventory gemspec file is changed to:
spec.summary       = %q{Write a short summary. Required.}
spec.description   = %q{Write a longer description. Optional.}

**Comment by werebus** [comment] 2016-07-15 13:11
Sure, or you could actually describe whatever this gem does...

**Comment by phantompatrol** [comment] 2016-07-15 13:26
@werebus Quite!

Not trying to hide behind the veil of this gem being an 'alpha', 'WIP', or whatever... I was more interested in using this issue pedagogically, to build up best practices. Practices that I myself am [guil](https://github.com/umts/aggressive_inventory/commit/72d7edc5aa1c0fd1dd1b417048702e8905c5eed1)ty of circumventing or outright breaking. In this case using a flow like:

Bug -> Issue -> Fork -> Branch -> Pull Request -> Review -> Merge

So, when this bug was discovered, we agreed to push it up as an issue rather than just patching, or fixing it with a contextless PR. And we will get all of the above steps covered, along with gem version management. It might be [half the distance to progress](https://en.wikipedia.org/wiki/Zeno%27s_paradoxes) but, I want every day to be better than the previous.

**Comment by werebus** [comment] 2016-07-15 13:33
:neutral_face: O.K..... :question:

**Comment by phantompatrol** [comment] 2016-07-15 13:35
@werebus Is that an objection? I am a little confused

**Comment by werebus** [comment] 2016-07-15 13:38
Likewise. I appear to have tread on a strong opinion about... something.  I'm not sure what you were saying above at all.

I was just suggesting that simply removing the word "TODO" didn't seem to be the best fix for this particular problem. Use whatever workflow you think is best to effect the fix.

**Comment by phantompatrol** [comment] 2016-07-15 13:53
Ah! No one was suggesting that removing the `TODO` was the fix, we just poked at it briefly on our way out the door yesterday.

I was try to address your [point](https://github.com/umts/aggressive_inventory/issues/2#issuecomment-232946973). Not trying to make a mountain out of a `todo` hill.
- We noticed it was broken
- Submitted an issue
- We have not pushed any code to fix the issue

**Comment by werebus** [comment] 2016-07-15 15:05
Ah.  It turns out that this was a misunderstanding mostly caused by _my_ tone. If there's one thing I should have learned on the internet by now, it's that good-natured sarcasm can often come across as meanness (especially if the two people have never met). Sorry about that, @Cobchise 

Anyways.  Yes, that workflow is a good idea:tm:, and both @Cobchise and I had independently sussed out the issue. My comment was only meant to propose a refinement to the fix proposed.

**Closed as completed** 2016-07-15 19:48 UTC
